version: "3.8"
services:
  otel-jeager-demo:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - jaeger

  jaeger:
    hostname: jeager
    image: jaegertracing/all-in-one:latest
    ports:
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
